# **Formulario Python para MAT4141**

### Importar bibliotecas o librerías

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Generar un DataFrame de nombre **df_1** a partir de un archivo (Excel o CSV) con base de datos subido al entorno en VSCode

In [9]:
# Cargar el DataFrame 
df_1 = pd.read_excel('Base_Netflix.xlsx')
df_1

,ID,Tipo,Título,País,Año,Duración,Categoría
0,s47,Película,Safe House,"South Africa, United States, Japan",2012,115 min,Acción y Aventura
1,s82,Película,Kate,United States,2021,106 min,Acción y Aventura
2,s136,Película,Cliffhanger,"United States, Italy, France, Japan",1993,113 min,Acción y Aventura
3,s142,Película,Extraction,"United States, United Kingdom, Canada",2015,82 min,Acción y Aventura
4,s229,Película,The November Man,"United States, United Kingdom",2014,108 min,Acción y Aventura
...,...,...,...,...,...,...,...
7090,s1066,TV Show,Slasher,Canada,2019,3 Seasons,Horror
7091,s1702,TV Show,American Horror Story,United States,2019,9 Seasons,Horror
7092,s5889,TV Show,Hemlock Grove,United States,2015,3 Seasons,Horror
7093,s6918,TV Show,Hannibal,United States,2015,3 Seasons,Horror
7094,s5264,TV Show,Dark Matter,Canada,2017,3 Seasons,Ciencia Ficción

### Agrupar datos en una tabla de frecuencia

In [10]:
## Codigo para agrupar datos
Categoría = df_1.groupby('Categoría').size()
Categoría

Categoría
Acción y Aventura        856
Anime                    173
Ciencia Ficción           14
Clásicos                 100
Comedia                 1266
Crimen                   358
Documental               759
Docuseries               175
Dramas                  1593
Horror                   273
Musical                   15
Niños                    318
Películas                165
Películas familiares     500
Reality Show              99
Romántico                 35
Stand-Up Comedy          334
Thrillers                 62
dtype: int64

### Tabla de frecuencia puntuales f y h. Variable Ordinal, Nominal y Discreta

In [11]:
## Codigo para agrupar datos
Categoría = df_1.groupby('Categoría').size()

Tabla_Frecuencia_Categorias = pd.DataFrame({
    'Frecuencia absoluta (f)': Categoría,
    'Frecuencia relativa (%) (h)': round((Categoría / 7095) * 100, 1)
})
Tabla_Frecuencia_Categorias

                      Frecuencia absoluta (f)  Frecuencia relativa (%) (h)
Categoría
Acción y Aventura                         856                         12.1
Anime                                     173                          2.4
Ciencia Ficción                            14                          0.2
Clásicos                                  100                          1.4
Comedia                                  1266                         17.8
Crimen                                    358                          5.0
Documental                                759                         10.7
Docuseries                                175                          2.5
Dramas                                   1593                         22.5
Horror                                    273                          3.8
Musical                                    15                          0.2
Niños                                     318                          4.5
Películas                                 165                          2.3
Películas familiares                      500                          7.0
Reality Show                               99                          1.4
Romántico                                  35                          0.5
Stand-Up Comedy                           334                          4.7
Thrillers                                  62                          0.9

### Tabla de frecuencia puntuales y acumuladas (f,h,F y H) Variable Cuantitativa Discreta

In [12]:
## Codigo para agrupar datos
Categoría = df_1.groupby('Categoría').size()

## Codigo para crear las frecuencias puntuales y acumuladas (f,h,F y H)
Tabla_Frecuencia_Categorias = pd.DataFrame({
    'Frecuencia absoluta (f)': Categoría,
    'Frecuencia absoluta acumulada (F)': Categoría.cumsum(),
    'Frecuencia relativa (%) (h)': round((Categoría / 7095) * 100, 1),
    'Frecuencia relativa acumulada (%) (H)': round((Categoría/7075 * 100),1).cumsum()
})
Tabla_Frecuencia_Categorias

,Frecuencia absoluta (f),Frecuencia absoluta acumulada (F),Frecuencia relativa (%) (h),Frecuencia relativa acumulada (%) (H)
Categoría,,,,
Acción y Aventura,856,856,12.1,12.1
Anime,173,1029,2.4,14.5
Ciencia Ficción,14,1043,0.2,14.7
Clásicos,100,1143,1.4,16.1
Comedia,1266,2409,17.8,34.0
Crimen,358,2767,5.0,39.1
Documental,759,3526,10.7,49.8
Docuseries,175,3701,2.5,52.3
Dramas,1593,5294,22.5,74.8
Horror,273,5567,3.8,78.7
Musical,15,5582,0.2,78.9
Niños,318,5900,4.5,83.4
Películas,165,6065,2.3,85.7
Películas familiares,500,6565,7.0,92.8
Reality Show,99,6664,1.4,94.2
Romántico,35,6699,0.5,94.7
Stand-Up Comedy,334,7033,4.7,99.4
Thrillers,62,7095,0.9,100.3

### Tabla de frecuencia variable Cuantitativa Continua

In [13]:
## Tabla de frecuencia Variable Cuantitativa Continua

##  k = Cantidad de intervalos 
##  n = Tamaño de la muestra 
##  d = Cantidad de decimales de los intervalos 

#Crearemos una nueva columna llamada Intervalos_tiempo
df_1['Intervalos_tiempo'] = pd.cut(df_1['Tiempo (en minutos)'], bins = k, include_lowest= True, precision = d)

#Calcularemos la frecuencia absoluta de la variable Intervalos_tiempo
cuenta_intervalos_tiempo = df_1.groupby('Intervalos_tiempo', observed = True).size()



## Asignar las etiquetas de cada frecuencia 
tabla_7 = pd.DataFrame({
    'Frecuencia absoluta (f)': cuenta_intervalos_tiempo,
    'Frecuencia absoluta acumulada (F)': cuenta_intervalos_tiempo.cumsum(),
    'Frecuencia relativa (%) (h)': cuenta_intervalos_tiempo/n * 100,
    'Frecuencia relativa acumulada (%) (H)': (cuenta_intervalos_tiempo/n * 100).cumsum()
})
tabla_7

KeyError: 'Tiempo (en minutos)'

### Calcular la cantidad de intervalos variable Cuantitativa Continua

In [ ]:
## La cantidad de intervalos I(n) depende del tamaño de la muestra n
## Modelado por la función I(n)= 1+3.3*Log10(n)
import numpy as np

Cantidad_intervalos = round(1+3.3*np.log10(250))    ## Tamaño de la muestra = 250
print(Cantidad_intervalos)

### Gráfico Circular o de torta
Variable = Nominal, Ordinal, Discreta

In [ ]:
# Importar bibliotecas o librerías
import matplotlib.pyplot as plt
import numpy as np

#Gráfico circular

#Considerar que "tabla" es el nombre de la tabla de frecuencias construida
categorias = tabla.index  #Indices de la tabla
h = tabla['Frecuencia']   #Considerar que "Frecuencia" es el tipo de frecuencia a graficar

#Gráfico
fig,ax = plt.subplots(figsize = (6,4)) #Tamaño de la figura
circular = ax.pie(h, labels = categorias, autopct= '%.1f%%')

#Personalización
ax.set_title('Título del gráfico')

plt.show()

### Gráfico de barras (Columnas)
Variable = Nominal, Ordinal, Discreta

In [ ]:
#Gráfico de barras (Columnas)

#Considerar que "tabla" es el nombre de la tabla de frecuencias construida

# Importar bibliotecas o librerías
import matplotlib.pyplot as plt
import numpy as np

#Variables
categorias = tabla.index
f = tabla['Frecuencia']   #Considerar que "Frecuencia" es el tipo de frecuencia a graficar

#Gráfico
fig, ax = plt.subplots(figsize = (6,6))
barras = ax.bar(categorias, f, color = 'r', edgecolor ='black') #Los colores son de libre elección

#Personalización
ax.set_title('Título del gráfico')
ax.set_xlabel('Título eje x')
ax.set_ylabel('Título eje y')
ax.bar_label(barras)
plt.xticks(rotation=45) #Rota en 45° las categorías para evitar la superposición
plt.show()

### Gráfico de barras
Variable = Nominal, Ordinal, Discreta

In [ ]:
#Gráfico de barras

#Considerar que "tabla" es el nombre de la tabla de frecuencias construida

# Importar bibliotecas o librerías
import matplotlib.pyplot as plt
import numpy as np

#Variables
categorias = tabla.index
f = tabla['Frecuencia']   #Considerar que "Frecuencia" es el tipo de frecuencia a graficar

#Gráfico
fig, ax = plt.subplots(figsize = (6,6))
barras = ax.barh(categorias, f, color = 'r', edgecolor ='black') #Los colores son de libre elección

#Personalización
ax.set_title('Título del gráfico')
ax.set_xlabel('Título eje y')
ax.set_ylabel('Título eje x')
ax.bar_label(barras)
plt.xticks(rotation=45) #Rota en 45° las categorías para evitar la superposición
plt.show()

In [ ]:
#Histograma

#Considerar que "tabla" es el nombre de la tabla de frecuencias construida

# Importar bibliotecas o librerías
import matplotlib.pyplot as plt
import numpy as np

#Variables
categorias = tabla.index
f= tabla['Frecuencia']   #Considerar que "Frecuencia" es el tipo de frecuencia a graficar

#Gráfico
fig, ax = plt.subplots(figsize = (7,5))
histograma= ax.bar(categorias.astype(str), f, color = 'r', edgecolor = 'black', width = 1) #Los colores son de libre elección

#Personalización
ax.set_title('Título del gráfico')
ax.set_xlabel('Título eje x')
ax.set_ylabel('Título eje y')
ax.bar_label(histograma, fmt = '%.1f%%') #El argumento fmt controla la cantidad de decimales a mostrar
plt.xticks(rotation=45, ha = 'right') #Rota en 45° las categorías para evitar la superposición
plt.show()

### Medidas de posición y dispersión para una variable cuantitativa

In [ ]:
media = df['Nombre de la variable'].mean()

mediana = df['Nombre de la variable'].median()

moda = df['Nombre de la variable'].mode()

percentil_k = df['Nombre de la variable'].quantile(k) #ingrese el valor "k" en decimal

desviacion_estandar = df['Nombre de la variable'].std()